name: CI/CD Dry Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
         distribution: 'adopt'
         java-version: '22'

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory
        run: ls -la target

      - name: Run Unit Tests
        run: mvn test

      - name: Mock Deployment (Dry Run)
         environment:staging  # Dry run in staging environment
        run: |
          echo "Simulating deployment to staging..."
          mkdir -p /tmp/staging-server
          cp target/*.jar /tmp/fake-server/
          echo "Fake server setup complete in staging."
