name: CI/CD Dry Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
         distribution: 'adopt'
         java-version: '22'

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory
        run: ls -la target

      - name: Run Unit Tests
        run: mvn test

     # - name: Mock Deployment (Dry Run)
        # environment:staging  # Dry run in staging environment
        #run: |
         # echo "Simulating deployment to staging..."
         # mkdir -p /tmp/staging-server
          #cp target/*.jar /tmp/staging-server/
          #echo "Fake server setup complete in staging."


      # Step 6: Mock the deployment process to a fake server
      - name: Mock Deployment to Fake Server
        run: |
          echo "Starting mock deployment to fake server..."
          
          # Simulate transferring files to a fake server (local directory in this case)
          DEPLOY_DIR="/tmp/fake-server"
          echo "Creating mock server directory at $DEPLOY_DIR"
          mkdir -p $DEPLOY_DIR
          echo "Copying application JAR to the mock server directory..."
          cp target/*.jar $DEPLOY_DIR/
          
          echo "Files deployed to mock server at $DEPLOY_DIR"

     
      - name: Start Mock Server
        run: |
         nohup python3 -m http.server 8080 &
         sleep 5  # Give the server time to start

      - name: Simulate Interaction with Mock API
        run: |
        echo "Sending deployment status to mock API: http://localhost:8080/api/deploy-status"
        RESPONSE=$(curl -s -X POST http://localhost:8080/api/deploy-status -d '{"status": "successful"}'
        )
        echo "Received mock API response: $RESPONSE"
      
      # Step 8: Simulate a health check after deployment
      - name: Mock Health Check on Server
        run: |
          echo "Simulating health check on the fake server..."
          
          # Simulate a server health check (mock check for deployed files)
          if [ -f /tmp/fake-server/*.jar ]; then
            echo "Health check passed! Application is up and running on mock server."
          else
            echo "Health check failed! Application is not deployed correctly."
            exit 1  # Exit with failure code if health check fails
          fi
      # Step 9: Mock notification (optional)
      - name: Notify Completion
        run: echo "Mock deployment completed successfully. Notifying stakeholders..."
