name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    # New Step: Clear Maven Cache (optional)
    - name: Clear Maven Cache
      run: mvn dependency:purge-local-repository

    # New Step: Update Dependencies
    - name: Update Dependencies
      run: mvn -U clean install

    # Existing Step: Build and Install Dependencies
    - name: Build and Install Dependencies
      run: mvn clean install -X
      
    - name: Package the Project
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
