name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Set up Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        echo "CHROME VERSION: $CHROME_VERSION"
        curl -sS -o chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    # New Step: Clear Maven Cache (optional)
    - name: Clear Maven Cache
      run: mvn dependency:purge-local-repository

    # Existing Step: Build and Install Dependencies
    - name: Build and Install Dependencies
      run: mvn clean install -X
      
    - name: Package the Project
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
